[phases.setup]
aptPkgs = ["ffmpeg", "libavcodec-dev", "libavformat-dev", "libavutil-dev", "libswresample-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.api.main:app --host 0.0.0.0 --port $PORT"
